<?php

namespace App\DataFixtures;

class AppFixtures extends Fixture
{
    // defines reference names for instances of Rooms
    private const BAGAGERIE = 'bagagerie';
    private const LOCAL = 'local';
    private const SALLE_SERVEUR_FOYER = 'salle serveur foyer';
    private const SALLE_SERVEUR_U1 = 'salle serveur U1';

    /**
     * Generates initialization data for rooms : [title]
     * @return \\Generator
     */

    private static function roomDataGenerator()
    {
        yield [0
        yield ["400 guitars collection", self::SLASH_RACK_1];
    }

    /**
     * Generates initialization data for film recommendations:
     *  [film_title, film_year, recommendation]
     * @return \\Generator
     */
    private static function guitarsGenerator()
    {
        yield [self::OLIVIER_RACK_1, "Epiphone SG Special P-90"];
        yield [self::OLIVIER_RACK_1, "Ibanez SA360NQM"];
        yield [self::SLASH_RACK_1, "Gibson Les Paul 1960"];
    }

    public function load(ObjectManager $manager)
    {
        $inventoryRepo = $manager->getRepository(Rack::class);

        foreach (self::rackDataGenerator() as [$title, $rackReference] ) {
            $rack = new Rack();
            $rack->setTitle($title);
            $manager->persist($rack);
            $manager->flush();

            // Once the Rack instance has been saved to DB
            // it has a valid Id generated by Doctrine, and can thus
            // be saved as a future reference
            $this->addReference($rackReference, $rack);
        }

        foreach (self::guitarsGenerator() as [$rackReference, $model])
        {
            // Retrieve the One-side instance of Rack from its reference name
            $rack = $this->getReference($rackReference);
            $guitar = new Guitar();
            $guitar->setDescription($model);
            // Add the Many-side Guitar to its containing rack
            $rack->addGuitar($guitar);

            // Requir that the ORM\OneToMany attribute on Rack::guitars has "cascade: ['persist']"
            $manager->persist($rack);
        }
        $manager->flush();
    }
}